### ISSUE TITLE
3D ndarray에 대한 np.fliplr 문제

### ISSUE THREAD

**Issue by alleysark** [reinforcement-learning-kr/alpha_omok#114]
안녕하세요! RLKorea의 알파오목을 참고하며 많은 도움을 받았습니다!
이리저리 실험을 하다가 학습된 정책에 비정상적인 대칭성이 발견되어서 디버깅하던 도중 `np.fliplr`이 3D ndarray에 대해서 의도와 다르게 동작하는 것을 발견했습니다.

```
# alpha_omok/2_AlphaOmok/utils.py:235
s_flip = np.fliplr(s_rot).copy()
pi_flip = np.fliplr(pi_rot).flatten().copy()
```

여기서 `pi_rot`은 2D array라서 의도한대로 좌우 반전을 합니다. 하지만 `s_rot`의 경우 3D array인데 `fliplr`시 상하반전이 되더군요. `fliplr`이 단순히 1번 축에대해 반전하도록 구현되어 있나봅니다.

따라서 이 부분을 `np.flip`을 사용해 다음과같이 수정해야 의도하는 좌우반전이 되는 것 같습니다.

```
s_flip = np.flip(s_rot, 2).copy()
pi_flip = np.fliplr(pi_rot).flatten().copy()
```

**Comment by kekmodel** [comment]
오오 확인했습니다. 감사합니다!

**Comment by kekmodel** [comment]
수정완료!
