### ISSUE TITLE
학습안되는 것을 해결하기 위해 따로 디버깅 폴더 만들어서 테스트

### ISSUE THREAD

**Issue by dnddnjs** [reinforcement-learning-kr/alpha_omok#20]
디버깅용 폴더를 따로 만들어서 다음 과정으로 테스트 해볼 예정
1. 네트워크를 최대한 간소화
2. tree search 과정 없이 강화학습만 해서 loss가 주는지 확인
3. 강화학습 과정이 확인되면 tree search를 붙여보기

@Kyushik

**Comment by Kyushik** [comment]
일단 test 버전으로 따로 폴더를 제작한거니까 내용 수정에 대한 문제도 없을 것 같구요! 일단 간소화 시킨 강화학습 버전으로 테스트해보는 것도 좋은 아이디어인 것 같습니다. 일단 이대로 한번 머지할게요!

**Comment by Kyushik** [comment]
@kekmodel  일단 어제 내용에 대해 정대님께도 공유드리자면 

1. Tree를 제외한 강화학습만 하는 버전을 만들고 이게 loss가 잘 줄어들고 어느 정도 학습이 잘 되면 여기에 tree를 붙이는 과정으로 진행하기로 했습니다. 
2. 내용을 살펴보던 중에 action 선택이 tau에 따라 pi max를 선택하거나 / random action을 선택하거나 이렇게 2가지였던 것 같은데, tau는 action 선택 equation의 지수로 들어가고 그 equation의 결과에 따라 확률적으로 action을 선택하는 방식으로 수정하는 것이 좋겠다고 이야기를 하였습니다. 
3. 학습이 잘 안되는 부분에 대해서는 dataset, exploration, network model 이렇게 3가지가 있을 것이라고 생각했습니다. 그래서 일단 강화학습만으로 학습이 되는 것을 보고 트리를 붙여보려고 했지요 ㅎㅎ

**Comment by kekmodel** [comment]
1번에서 강화학습이 어떤 방법으로 진행되는지 알고 싶습니다. Actor-Critic 으로 된다고 보면 될까요?
2번은 tau를 어떻게 쓰는 건가요? 논문에서 tau는 30수까지는 1 그 이후로는 0으로 셀프플레이를 한다고 나와있는데요. 그 사이 값도 쓰신다는 건가요?
![screenshot from 2018-05-12 14-05-55](https://user-images.githubusercontent.com/7728527/39953773-b4676e2a-55ed-11e8-8485-a0d24726ca4b.png)
(tau -> 0 의 의미)
![screenshot from 2018-05-12 14-08-40](https://user-images.githubusercontent.com/7728527/39953795-09c819c8-55ee-11e8-96e1-1d13a1f5690b.png)

3번은 저도 동의 합니다. 추가적으로 **train 방법, node와 state의 불일치 문제** 도 생각해볼 수 있을 것 같습니다.

**Comment by dnddnjs** [comment]
이 부분이겠죠? 
<img width="655" alt="2018-05-12 5 51 26" src="https://user-images.githubusercontent.com/16641054/39955645-51e0bd40-560d-11e8-8682-33a731f5c032.png">

**Comment by dnddnjs** [comment]
애초에 알파고나 알파고 제로가 액터크리틱이 아니라서 그냥 REINFORCE 에이전트입니다. 셀프 플레이 데이터로부터 학습합니다. 보상을 받게 한 행동의 probability를 높이는 식으로 학습하는거죠.

**Comment by kekmodel** [comment]
Z로 그걸 평가하잖아요?

**Comment by kekmodel** [comment]
흠 그렇군요.
그래서 2번은 어떻게 적용하시는 거죠?

**Comment by dnddnjs** [comment]
노이즈를 추가안해주는 상황에서는 그냥 stochastic하게 선택하는게 좋을 것도 같습니다. 그리고 빠르게 테스트하는 거니까 굳이 temperature라는 파라메터를 도입하지 않는 것이 좋을 것 같아요 ㅎㅎ

**Comment by kekmodel** [comment]
네 알겠습니다!
