### ISSUE TITLE
모델 평가 파일 (evauator.py) 추가 제안

### ISSUE THREAD

**Issue by kekmodel** [reinforcement-learning-kr/alpha_omok#22]
**저장된 모델의 파라미터를 불러와서 대결. 승률과 ELO 점수 계산.**

기능1. 모델_new vs 모델_old
기능2. 모델_new vs PUCT

"기능1"의 목적: 학습의 진행정도에 따라 Policy가 개선되고 있는지 확인.
"기능2"의 목적: 절대적인 실력 확인. Random Policy 기반의 PUCT를 base로 잡아 어느 정도 실력인지 확인. 
<br>
*PUCT:  모델이 없는 MCTS 버전. P = 1 / 착수가능 수의 개수, V = Random Rollout의 결과 사용.*
<br>
**평가 방법**
* 시뮬레이션 횟수는 400회로 통일.
* Dirichlet Noise 사용 안함.
* 항상 Greedy하게 Action 선택.
* 대결 횟수 30회.
* 승률: (승리 수 + 0.5 x 무승부 수) / 전체 대결 수
* ELO 점수: PUCT를 0점으로 계산. k-factor = 32. (참고: https://en.wikipedia.org/wiki/Elo_rating_system)

**Comment by dnddnjs** [comment]
이전 모델이랑 붙여서 테스트하는 건 좋다고 생각합니다. 
대결 횟수는 좀 많은 것 같고 항상 greedy 하게 action 선택하면 안될 것 같습니다. 
그냥 mcts의 output인 pi의 확률에 따라 확률적으로 선택해야할 것 같습니다.

**Comment by kekmodel** [comment]
실제 대결 시의 성능을 알아보는 모드이므로 실제 대결처럼 greedy하게 선택하는 것으로 판단하는 것이 좋지 않을까요? (tau -> 0)
![screenshot from 2018-05-12 14-00-09](https://user-images.githubusercontent.com/7728527/39953752-0a21a61a-55ed-11e8-8d16-4456000906c5.png)

 ELO  점수를 계산하기 위해선 30판 정도의 데이터는 필요합니다!
그리고 이 과정은 학습과정에 들어가지 않고, 테스트용 파일. evaluator.py로 따로 만드려고 하는 거여서 횟수는 사실 크게 중요하진 않습니다. 얘네는 400판 붙이네요.

**Comment by dnddnjs** [comment]
흠 그렇군요. 일단 그러면 greedy 하게 해도 괜찮을 것 같습니다 ㅎㅎ

**Comment by Kyushik** [comment]
넵 ㅎㅎ 테스트용이면 greedy하게 진행해도 괜찮을 수 있겠네요
일단은... 학습 자체가 잘 안되는게 먼저 해결되어야할 것 같긴한데.. 이쪽도 필수적으로 개발되어야하는 내용인만큼 진행해도 좋을 것 같습니다 ㅎㅎ 
투트랙으로 진행하던지, 일단 진행 방법에 대해서는 조금 더 고민해보도록 하겠습니다.

**Comment by kekmodel** [comment]
https://github.com/reinforcement-learning-kr/alpha-omok/pull/30

**Comment by kekmodel** [comment]
**기능 구현 및 변경사항**
- 기능1. 모델_new vs 모델_old
- 기능2. 모델_new vs PUCT
- 기능3. 모델 vs Random
- 모델 초기화 kaiming_nomal -> kaiming_uniform 으로 변경 (학습 테스트)
- agent.py에 random agent, puct agent 추가
- pep8 style 로 자동 변경된 부분 일부 있음


**현재 평가 방법**
- 시뮬레이션 횟수는 400회로 통일.
- 항상 Greedy하게 Action 선택.
- 대결 횟수 30회.
- 승률: (승리 수 + 0.5 x 무승부 수) / 전체 대결 수

**Comment by Kyushik** [comment]
현재 디버깅 관련 사항 
- PUCT agent가 valid하지 않은 action을 수행하는 오류 (시뮬레이션을 적게 돌렸을 때 발생)
- turn 변경은 검증 완료 -> enemy가 여러번 두는 문제도 해결
