### ISSUE TITLE
레포지토리 이름 변경 및 바둑 폴더 제거

### ISSUE THREAD

**Issue by dnddnjs** [reinforcement-learning-kr/alpha_omok#28]
레포지토리 이름을 alphaomok이나 alpha_omok으로 하는게 어떨까요?
그리고 go 관련해서 만들어놓은 폴더를 지우는게 어떨까요?

**Comment by kekmodel** [comment]
동의합니다.

**Comment by Kyushik** [comment]
넵! 이건 바로 진행하겠습니다 ㅎㅎ

**Comment by Kyushik** [comment]
이 부분에 대한 pull request 올렸습니다! close 하겠습니다~ ㅎㅎ
