### ISSUE TITLE
강화학습 에이전트로 PUCT 에이전트(simulation 400회) 이기기

### ISSUE THREAD

**Issue by dnddnjs** [reinforcement-learning-kr/alpha_omok#47]
기존 알파제로 에이전트가 학습이 안되는 문제를 해결하기 위해 강화학습 만으로 학습.
학습한 에이전트가 MCTS 400회 돌린 에이전트와 붙어서 이길 정도로만 강화학습 시킴.
그 이후에 MCTS를 붙여서 알파제로 알고리즘 만들 계획

**Comment by kekmodel** [comment]
### 180602-180604 제로 에이전트 학습 기록

학습방법: 

	400게임 후 (메모리에 약 13만 샘플 저장) 메모리에서 랜덤 샘플링하여 100step 학습하고 메모리 비움

세팅:

	BOARD_SIZE = 9
	N_MCTS = 400
	TAU_THRES = 6
	N_BLOCKS = 10
	IN_PLANES = 5
	OUT_PLANES = 64
	N_SELFPLAY = 400
	N_EPOCHS = 1
	N_SAMPLING = 100
	BATCH_SIZE = 32
	LR = 0.01
	L2 = 1e-4
	Optimizer: Momentum 0.9


100step model

	VS. None        6:4
	VS. puct400	1:9


200step model

	VS. None        8:2
	VS. 100step	8:2
	VS. puct400	1:9


300step model

	VS. None        5:5
	VS. 100step     6:4 
	VS. 200step	4:6
	VS. puct400	2:8

400step model

	VS. 200step	0:10

**학습 중단**
눈물이 납니다...
