### ISSUE TITLE
Dataset Augmentation

### ISSUE THREAD

**Issue by kekmodel** [reinforcement-learning-kr/alpha_omok#68]
학습속도를 빠르게하기 위해서 train전에 데이터를 대칭변환으로 Augmentation하는 기능이 있으면 좋을 것 같습니다. 이전에 만든 함수는 현재 state의 대칭변환 중 하나를 랜덤 선택하여 리턴하는 함수였는데 랜덤 선택이 아니라 가능한 변환 전부를 데이터 셋에 포함시켜서 학습하면 확실히 빨리 늘지 않을까 싶습니다.

**Comment by Kyushik** [comment]
논문에서도 변환 전부를 이용해서 augmentation 했죠? 랜덤선택해서 리턴하는걸 전부 변환하도록 변경만 해주면 되는 부분인가요? ㅎㅎ

**Comment by kekmodel** [comment]
네 알파고 제로에선 적용하여 학습했고, MCTS의 확장단계에서 state를 8대칭 중 하나를 랜덤 선택해서 평가합니다.
아직 흑백반전은 구현안돼어 있고, 변경후 저장해서 메모리에 다시 넣어줘야해서 바로 될 것 같진 않은데 조금 고민해보면 되겠죠? ㅎㅎ

**Comment by Kyushik** [comment]
@kekmodel 잘 마무리 된 것 같네요! 이상 없는지 8번 gpu로 처음부터 돌려보겠습니다! 수고 많으셨습니다~ 감사합니다 👍
