### ISSUE TITLE
Master로 merge하기!

### ISSUE THREAD

**Issue by Kyushik** [reinforcement-learning-kr/alpha_omok#69]
저희 이번 7월 7일 중간발표 때 master에 한번 merge하는게 어떨까요? 
무려 developer가 master에 비해 100 커밋 이상 앞서있네요 ㅎㅎㅎ
master로 merge 전에 개인적으로 진행하신 부분들에 최종적으로 이상이 없는지  재확인 부탁드릴게요!

**Comment by kekmodel** [comment]
저는 현재 돌리고 있는데 이상없습니다!

**Comment by Kyushik** [comment]
@tykimos  태영님 내용 정리되시는대로 master로 merge하도록 하겠습니다!
